# Use an official Python runtime as a parent image
FROM python:3.12

EXPOSE 8888
WORKDIR .

RUN pip install jupyter
ENV NAME World

COPY ./requirements.txt .

RUN pip install -r requirements.txt

COPY . .

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]